# Generated by Django 2.1.1 on 2018-10-31 14:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='保存日期')),
                ('reporter', models.CharField(max_length=100, verbose_name='保存日期')),
                ('status', models.CharField(max_length=100, verbose_name='保存日期')),
            ],
            options={
                'verbose_name': '跑批信息',
                'verbose_name_plural': '跑批信息',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, verbose_name='登录名')),
                ('password', models.CharField(max_length=100, verbose_name='密码')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('log', models.TextField(max_length=100, verbose_name='日志内容')),
                ('email', models.CharField(max_length=100, verbose_name='邮箱')),
                ('status', models.CharField(max_length=100, verbose_name='状态')),
                ('name_pinyin', models.CharField(max_length=100, verbose_name='拼音')),
            ],
            options={
                'verbose_name': '日志内容',
                'verbose_name_plural': '日志内容',
            },
        ),
    ]
